services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      APPLICATION_NAME: ecommerce-backend
      SPRING_PROFILES_ACTIVE: prod
      PROFILE: prod
      PORT: 8080
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ecommerce
      DB_USER: ecommerce_user
      DB_PASSWORD: ecommerce_pass
      DDL_MODE: update
      FRONT_END_URL: "http://frontend:3000"
    depends_on:
      db:
        condition: service_healthy # <--- Nueva condiciÃ³n

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      EXTERNAL_API_URL: "http://backend:8080"
    depends_on:
      - backend

  db:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: ecommerce_pass
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mariadb -u root -prootpass -h 127.0.0.1 -e 'SELECT 1;' $MYSQL_DATABASE"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s # Espera 20 segundos antes de empezar a chequear
