spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST:db}:${DB_PORT:3306}/${DB_NAME:ecommerce}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:ecommerce_user}
    password: ${DB_PASSWORD:ecommerce_pass}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_MODE:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
