spring:
  # Para usar arhivo .env (ubicación: junto a pom.xml)
  #config:
  #  import: optional:file:.env[.properties]

  application:
    name: ${APPLICATION_NAME:ecommerce}

  profiles:
    active: ${PROFILE:dev}

  server:
    port: ${PORT:8080}

  http:
    encoding:
      force: true
      enable: true
      charset: UTF-8

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

frontend:
    url: ${FRONT_END_URL:http://localhost:3000}

springdoc:
  api-docs:
    default-produces-media-type: application/json
    default-consumes-media-type: application/json
  swagger-ui:
    path: /docs

# Aumento el nivel de log para ver más info
#logging:
#  level:
#    org.springdoc: DEBUG
#    org.spingframework.web: DEBUG
